#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# take input for variable file
VARFILE="$1"
if ! [[ -e "$VARFILE" ]]; then
  echo "variable file $VARFILE not found"
  exit 1
fi

# change to project root dir
SCRIPT_PATH=$(realpath "$0")
SCRIPT_PATH="${SCRIPT_PATH/build/}"
cd "$SCRIPT_PATH"

# kill all child proceses
kill_spawn() {
  for SPAWN in $(pgrep -g $$); do
    kill -2 "$SPAWN"
  done
}

# kill_spawn on exit and ctrl-c
trap kill_spawn EXIT SIGINT

# start full build
if [[ $(arch) =~ "arm64" ]]; then
  (
    PACKER_LOG=1 packer build -force -only base.tart-cli.macOS -var-file "$VARFILE" macOS.pkr.hcl
  ) &
elif [[ $(arch) =~ "i386" ]]; then
  (
    packer build -force -only base.vmware-iso.macOS -var-file "$VARFILE" macOS.pkr.hcl &&
      packer build -force -only=customize.vmware-vmx.macOS -var-file "$VARFILE" macOS.pkr.hcl
  ) &
fi

# Wait for all builds to finish
wait

# end
echo "End of Line"
exit 0
